language: python
python:
  - "2.7"
  - "2.6"

python -m unittest discover -t 'tests' -p 'test*.py'
#script:  python -m unittest tests.test_tail_check_statistics tests.test_additivity_check_statistics #tests.test_curvature tests.test_ptrm_statistics 
# script:  python -m tests.test_fake  